export interface Heilige {
  naam: string;
  titel: string;
  kort: string;
  /** Heilige van de Lage Landen */
  nl?: boolean;
}

/** Curated Nederlandstalig menologion (kerkelijke datum M-D). */
export const HEILIGEN: Record<string, Heilige[]> = {
  '1-1': [{ naam: 'Basilius de Grote', titel: 'Aartsbisschop van Caesarea, kerkvader (†379)', kort: 'Theoloog van de Drie-eenheid, vader van het gemeenschappelijk kloosterleven; zijn Liturgie wordt op de zondagen van de Vasten gevierd.' }],
  '1-2': [
    { naam: 'Serafim van Sarov', titel: 'Wonderdoener (†1833)', kort: '„Verwerf de vrede in uw hart en duizenden rondom u zullen gered worden.” Duizend dagen en nachten bad hij op een steen.' },
    { naam: 'Silvester van Rome', titel: 'Paus (†335)', kort: 'Bisschop van Rome ten tijde van Constantijn de Grote en het Concilie van Nicea.' },
  ],
  '1-5': [{ naam: 'Syncletica van Alexandrië', titel: 'Woestijnmoeder (†ca. 350)', kort: 'Geestelijke moeder van vele ascetes; haar uitspraken staan in de Apophthegmata.' }],
  '1-9': [{ naam: 'Filippus van Moskou', titel: 'Metropoliet, martelaar (†1569)', kort: 'Weigerde Ivan de Verschrikkelijke te zegenen en betaalde met zijn leven.' }],
  '1-10': [{ naam: 'Gregorius van Nyssa', titel: 'Bisschop, kerkvader (†395)', kort: 'Broer van Basilius; mystiek theoloog van het „Leven van Mozes”.' }],
  '1-11': [{ naam: 'Theodosius de Grote', titel: 'Coenobiarch (†529)', kort: 'Vader van het gemeenschappelijk kloosterleven in Palestina.' }],
  '1-12': [{ naam: 'Tatiana van Rome', titel: 'Diacones, martelares (†226)', kort: 'Patrones van studenten; haar feest is in Rusland de Dag van de Student.' }],
  '1-14': [{ naam: 'Nina van Georgië', titel: 'Gelijk aan de apostelen (†335)', kort: 'Doopte Georgië met een kruis van wijnranken, gebonden met haar eigen haar.' }],
  '1-17': [{ naam: 'Antonius de Grote', titel: 'Vader van alle monniken (†356)', kort: 'Kluizenaar in de Egyptische woestijn; bestreed de demonen door gebed en arbeid.' }],
  '1-18': [{ naam: 'Athanasius en Cyrillus van Alexandrië', titel: 'Aartsbisschoppen, kerkvaders', kort: 'Verdedigers van de godheid van Christus (Nicea) en van de Moeder Gods (Efeze).' }],
  '1-19': [
    { naam: 'Macarius de Grote', titel: 'Woestijnvader van Egypte (†390)', kort: 'Leerling van Antonius; de geestelijke homilieën dragen zijn naam.' },
    { naam: 'Marcus van Efeze', titel: 'Metropoliet, belijder (†1444)', kort: 'Weigerde als enige de unie van Florence te ondertekenen.' },
  ],
  '1-20': [{ naam: 'Euthymius de Grote', titel: 'Abt in Palestina (†473)', kort: 'Stichter van de laura in de Judese woestijn; leraar van Sabbas.' }],
  '1-21': [{ naam: 'Maximus de Belijder', titel: 'Monnik, theoloog (†662)', kort: 'Verdedigde de twee willen van Christus; tong en hand werden hem afgesneden.' }],
  '1-22': [{ naam: 'Timoteüs', titel: 'Apostel, bisschop van Efeze', kort: 'Leerling van Paulus, ontvanger van twee brieven; gestenigd te Efeze.' }],
  '1-24': [{ naam: 'Xenia van Petersburg', titel: 'Dwaas om Christus (†ca. 1803)', kort: 'Na de dood van haar man leefde zij 45 jaar als zwerfster in gebed; helpster bij huisvesting, werk en huwelijk.' }],
  '1-25': [{ naam: 'Gregorius de Theoloog', titel: 'Aartsbisschop van Constantinopel (†389)', kort: 'Dichter en redenaar; zijn vijf theologische redes gaven hem de eretitel „de Theoloog”.' }],
  '1-27': [{ naam: 'Johannes Chrysostomus', titel: 'Overbrenging van de relieken (438)', kort: 'De Gouden Mond keert terug naar Constantinopel, dertig jaar na zijn dood in ballingschap.' }],
  '1-28': [{ naam: 'Efrem de Syriër', titel: 'Diaken, hymnendichter (†373)', kort: 'De „harp van de Geest”; dichter van het vastengebed „Heer en Meester van mijn leven”.' }],
  '1-30': [{ naam: 'De Drie Hiërarchen', titel: 'Basilius, Gregorius en Johannes Chrysostomus', kort: 'Gezamenlijk feest sinds de 11e eeuw; patroonsfeest van de theologische scholen.' }],
  '1-31': [{ naam: 'Cyrus en Johannes', titel: 'Onbaatzuchtige genezers, martelaren (†311)', kort: 'Arts en soldaat; genazen gratis te Alexandrië.' }],
  '2-1': [{ naam: 'Tryphon', titel: 'Martelaar (†250)', kort: 'Ganzenhoeder uit Lampsacus; beschermer van tuinen en velden tegen ongedierte.' }],
  '2-3': [{ naam: 'Simeon de Godontvanger en Anna de Profetes', titel: 'Rechtvaardigen', kort: 'De dag na de Ontmoeting worden de twee getuigen in de tempel geëerd.' }],
  '2-6': [{ naam: 'Fotios de Grote', titel: 'Patriarch van Constantinopel (†891)', kort: 'Geleerde en verdediger van de orthodoxie tegenover Rome; zond Cyrillus en Methodius uit.' }],
  '2-10': [{ naam: 'Charalampus', titel: 'Priester, martelaar (†202)', kort: 'Op 113-jarige leeftijd gemarteld; beschermer tegen besmettelijke ziekten.' }],
  '2-11': [{ naam: 'Blasius van Sebaste', titel: 'Bisschop, martelaar (†316)', kort: 'Arts en bisschop; aangeroepen bij keelaandoeningen (kaarsenzegen).' }],
  '2-12': [{ naam: 'Alexius van Moskou', titel: 'Metropoliet, wonderdoener (†1378)', kort: 'Genas de blinde vrouw van de Tataarse khan; geestelijk vader van Dmitri Donskoj.' }],
  '2-17': [{ naam: 'Theodorus de Rekruut (Tyro)', titel: 'Grootmartelaar (†306)', kort: 'Verbrandde de tempel van Cybele; het koliva-wonder wordt op de eerste vastenzaterdag herdacht.' }],
  '2-24': [{ naam: 'Vinding van het hoofd van Johannes de Doper', titel: 'Eerste en tweede vinding', kort: 'Het hoofd van de Voorloper werd tweemaal teruggevonden, in de 4e en de 5e eeuw.' }],
  '2-29': [{ naam: 'Cassianus de Romein', titel: 'Monnik, schrijver (†435)', kort: 'Alleen in schrikkeljaren gevierd; bracht de wijsheid van de woestijnvaders naar het Westen.' }],
  '3-9': [{ naam: 'Veertig Martelaren van Sebaste', titel: 'Soldaten, martelaren (†320)', kort: 'Op een bevroren meer gedreven in Armenië; slechts één week, de rest kreeg de kroon. Leeuwerikbroodjes in de Vasten.' }],
  '3-12': [{ naam: 'Gregorius de Dialoog', titel: 'Paus van Rome (†604)', kort: 'Gregorius de Grote; de Liturgie der Voorafgewijde Gaven draagt zijn naam.' }],
  '3-17': [{ naam: 'Alexius, de man Gods', titel: 'Asceet (†411)', kort: 'Verliet rijkdom en bruid; leefde onherkend als bedelaar onder de trap van zijn ouderlijk huis.' }],
  '3-18': [{ naam: 'Cyrillus van Jeruzalem', titel: 'Aartsbisschop, kerkvader (†386)', kort: 'Zijn Catechesen zijn de klassieke doopvoorbereiding van de vroege Kerk.' }],
  '3-26': [{ naam: 'Aartsengel Gabriël', titel: 'Synaxis', kort: 'Daags na de Annunciatie wordt de boodschapper van de menswording geëerd.' }],
  '3-30': [{ naam: 'Johannes Climacus', titel: 'Abt van de Sinaï (†649)', kort: 'Auteur van De Ladder van het Paradijs; herdacht op de 4e vastenzondag.' }],
  '4-1': [{ naam: 'Maria van Egypte', titel: 'Boetelinge (†522)', kort: 'Zeventien jaar zondares in Alexandrië, zevenenveertig jaar asceet in de woestijn over de Jordaan.' }],
  '4-11': [{ naam: 'Antipas van Pergamum', titel: 'Bisschop, martelaar (†92)', kort: 'Genoemd in de Openbaring (2:13); helper bij tandpijn.' }],
  '4-23': [{ naam: 'Georgius de Grootmartelaar', titel: 'Overwinnaar (†303)', kort: 'Drakendoder; patroon van Moskou, Georgië, Engeland en van alle soldaten.' }],
  '4-25': [{ naam: 'Marcus', titel: 'Apostel en evangelist', kort: 'Leerling van Petrus, stichter van de Kerk van Alexandrië.' }],
  '4-30': [{ naam: 'Jakobus, zoon van Zebedeüs', titel: 'Apostel', kort: 'Broer van Johannes de Theoloog; eerste apostel die de marteldood stierf.' }],
  '5-2': [{ naam: 'Athanasius de Grote', titel: 'Overbrenging van de relieken', kort: 'Patriarch van Alexandrië, de „pilaar van de orthodoxie” tegen het arianisme.' }],
  '5-8': [{ naam: 'Johannes de Theoloog', titel: 'Apostel en evangelist', kort: 'De geliefde leerling, evangelie van de adelaar; bij zijn graf te Efeze verscheen jaarlijks genezend stof.' }],
  '5-9': [{ naam: 'Nicolaas van Myra', titel: 'Overbrenging van de relieken naar Bari (1087)', kort: 'De „zomer-Nicolaas”: zijn mirre-uitstortende relieken rusten in Bari.' }],
  '5-11': [{ naam: 'Cyrillus en Methodius', titel: 'Gelijk aan de apostelen, leraren der Slaven', kort: 'Schepers van het Slavische alfabet en de Slavische liturgie.' }],
  '5-13': [{ naam: 'Servatius van Maastricht', titel: 'Bisschop (†384)', kort: 'Bisschop van Tongeren en Maastricht, tijdgenoot van Athanasius; oudste heilige van Nederland.', nl: true }],
  '5-21': [{ naam: 'Constantijn en Helena', titel: 'Gelijk aan de apostelen', kort: 'De eerste christelijke keizer en zijn moeder, vindster van het Kruis.' }],
  '5-25': [{ naam: 'Derde vinding van het hoofd van Johannes de Doper', titel: '(ca. 850)', kort: 'Het hoofd van de Voorloper keert terug naar Constantinopel.' }],
  '6-5': [{ naam: 'Bonifatius', titel: 'Aartsbisschop, martelaar te Dokkum (†754)', kort: 'Apostel van de Friezen en Germanen; met 52 gezellen bij Dokkum gedood.', nl: true }],
  '6-9': [{ naam: 'Cyrillus van Alexandrië', titel: 'Patriarch, kerkvader (†444)', kort: 'Verdediger van de titel Theotokos op het Concilie van Efeze (431).' }],
  '6-11': [{ naam: 'Bartolomeüs en Barnabas', titel: 'Apostelen', kort: 'Bartolomeüs predikte tot in Indië en Armenië; Barnabas was metgezel van Paulus.' }],
  '6-12': [
    { naam: 'Onuphrius de Grote', titel: 'Kluizenaar (4e eeuw)', kort: 'Zestig jaar alleen in de Egyptische woestijn, gekleed in zijn eigen haar.' },
    { naam: 'Odulfus van Utrecht', titel: 'Priester en missionaris (†ca. 855)', kort: 'Kanunnik van Utrecht, verkondiger onder de Friezen bij Stavoren.', nl: true },
  ],
  '6-19': [{ naam: 'Johannes van Shanghai en San Francisco', titel: 'Aartsbisschop, wonderdoener (†1966)', kort: 'Sliep nooit in een bed, diende dagelijks de Liturgie; als aartsbisschop van West-Europa bezocht hij ook de orthodoxe gemeenten in Nederland.' }],
  '6-24': [{ naam: 'Geboorte van Johannes de Doper', titel: 'Feest', kort: 'Zes maanden vóór Kerstmis; Zacharias’ mond wordt geopend.' }],
  '6-25': [{ naam: 'Adalbert van Egmond', titel: 'Diaken, missionaris (†740)', kort: 'Metgezel van Willibrord in Kennemerland; bij zijn graf ontstond de abdij van Egmond.', nl: true }],
  '6-29': [{ naam: 'Petrus en Paulus', titel: 'Opperapostelen', kort: 'De rots en de heidenapostel, samen gemarteld te Rome onder Nero.' }],
  '6-30': [{ naam: 'Synaxis van de Twaalf Apostelen', titel: 'Feest', kort: 'De twaalf gezamenlijk geëerd, de dag na Petrus en Paulus.' }],
  '7-1': [{ naam: 'Cosmas en Damianus van Rome', titel: 'Onbaatzuchtige artsen, martelaren (†284)', kort: 'Genazen gratis; door hun jaloerse leermeester gedood.' }],
  '7-2': [{ naam: 'Nederlegging van het gewaad van de Moeder Gods', titel: 'Feest (Blachernae, 5e eeuw)', kort: 'Het gewaad van Maria beschermde Constantinopel tegen belegeraars.' }],
  '7-5': [
    { naam: 'Athanasius van Athos', titel: 'Stichter van de Grote Laura (†1000)', kort: 'Grondlegger van het georganiseerde kloosterleven op de Heilige Berg.' },
    { naam: 'Sergius van Radonezj', titel: 'Vinding van de relieken (1422)', kort: 'De hegoumen van heel Rusland; stichter van de Drie-eenheidslaura.' },
  ],
  '7-8': [{ naam: 'Procopius', titel: 'Grootmartelaar (†303)', kort: 'Romeins officier, bekeerd door een verschijning van het Kruis.' }],
  '7-11': [{ naam: 'Olga van Kiev', titel: 'Gelijk aan de apostelen (†969)', kort: 'Eerste christelijke vorstin van Rusland; grootmoeder van Vladimir.' }],
  '7-12': [{ naam: 'Paisius de Athoniet', titel: 'Monnik, starets (†1994)', kort: 'Geliefde geestelijke vader van de Athos; heilig verklaard in 2015.' }],
  '7-15': [{ naam: 'Vladimir van Kiev', titel: 'Gelijk aan de apostelen (†1015)', kort: 'Doper van Rusland (988); van heidens vorst tot „de Rode Zon” van barmhartigheid.' }],
  '7-17': [{ naam: 'Marina (Margaretha) van Antiochië', titel: 'Grootmartelares (†304)', kort: 'Vijftienjarige die de duivel met een hamer sloeg; onthoofd onder Diocletianus.' }],
  '7-20': [{ naam: 'Profeet Elia', titel: 'Profeet (9e eeuw v.Chr.)', kort: 'Ten hemel gevoerd in een vurige wagen; patroon van regen en vliegeniers.' }],
  '7-22': [{ naam: 'Maria Magdalena', titel: 'Myrondraagster, gelijk aan de apostelen', kort: 'Eerste getuige van de Opstanding; volgens de overlevering bracht zij keizer Tiberius een rood ei.' }],
  '7-24': [{ naam: 'Boris en Gleb', titel: 'Passiedragers (†1015)', kort: 'Vorstenzonen die zich zonder verzet lieten doden door hun broer; eerste Russische heiligen.' }],
  '7-25': [{ naam: 'Ontslaping van Anna', titel: 'Moeder van de Moeder Gods', kort: 'De grootmoeder van Christus; patrones van zwangere vrouwen.' }],
  '7-26': [{ naam: 'Paraskevi van Rome', titel: 'Martelares (†140)', kort: 'Helpster bij oogaandoeningen.' }],
  '7-27': [{ naam: 'Pantelejmon', titel: 'Geneesheer, grootmartelaar (†305)', kort: 'Arts uit Nicomedië die gratis genas; „de albarmhartige”, aangeroepen bij ziekte.' }],
  '8-1': [{ naam: 'Zeven Makkabeeën, hun moeder Solomonia en Eleazar', titel: 'Martelaren (166 v.Chr.)', kort: 'Oudtestamentische martelaren; begin van de Dormitionvasten met de honingzegening.' }],
  '8-9': [{ naam: 'Matthias', titel: 'Apostel', kort: 'Gekozen in de plaats van Judas; predikte in Ethiopië.' }],
  '8-16': [{ naam: 'Icoon van Christus „niet door mensenhanden gemaakt”', titel: 'Overbrenging uit Edessa (944)', kort: 'De doek waarop Christus zelf Zijn gelaat afdrukte voor koning Abgar.' }],
  '8-17': [{ naam: 'Jeroen van Noordwijk', titel: 'Priester, martelaar (†856)', kort: 'Door de Noormannen gedood; zijn relieken rusten in Egmond en Noordwijk.', nl: true }],
  '8-20': [{ naam: 'Profeet Samuël', titel: 'Profeet en rechter', kort: 'Zalfde Saul en David tot koning.' }],
  '8-28': [{ naam: 'Mozes de Ethiopiër (de Zwarte)', titel: 'Woestijnvader (†ca. 400)', kort: 'Van roverhoofdman tot monnik in de Sketische woestijn; leraar van nederigheid en berouw — „wie zijn eigen zonden ziet, ziet die van zijn broeder niet”.' }],
  '8-29': [{ naam: 'Onthoofding van Johannes de Doper', titel: 'Feest en vastendag', kort: 'Herodes laat de Voorloper onthoofden op verzoek van Herodias.' }],
  '8-31': [{ naam: 'Nederlegging van de Gordel van de Moeder Gods', titel: 'Feest', kort: 'De gordel wordt bewaard in het Vatopediklooster op de Athos.' }],
  '9-1': [{ naam: 'Simeon de Styliet', titel: 'Pilaarheilige (†459)', kort: 'Zevenendertig jaar op een zuil bij Antiochië; begin van het kerkelijk jaar.' }],
  '9-5': [{ naam: 'Zacharias en Elisabeth', titel: 'Profeet en rechtvaardige', kort: 'Ouders van Johannes de Doper.' }],
  '9-6': [{ naam: 'Wonder van de Aartsengel Michaël te Chonae', titel: 'Feest', kort: 'Michaël redt de kerk en de bron van Chonae door de rivier in de rots te laten verdwijnen.' }],
  '9-9': [{ naam: 'Joachim en Anna', titel: 'Rechtvaardige voorouders van God', kort: 'De ouders van de Moeder Gods, daags na haar geboortefeest.' }],
  '9-10': [{ naam: 'Menodora, Metrodora en Nymphodora', titel: 'Martelaressen, zusters (†305)', kort: 'Drie maagdelijke zusters uit Bithynië, gemarteld bij de warmwaterbronnen van Pythias.' }],
  '9-11': [{ naam: 'Theodora van Alexandrië', titel: 'Boetelinge (†490)', kort: 'Leefde na haar val vermomd als monnik Theodorus in een mannenklooster.' }],
  '9-13': [{ naam: 'Cornelius de Honderdman', titel: 'Eerste heiden-bekeerling (Hand. 10)', kort: 'Door Petrus gedoopt te Caesarea; patroon van de orthodoxe parochie in Amersfoort.' }],
  '9-15': [{ naam: 'Nikita de Goth', titel: 'Grootmartelaar (†372)', kort: 'Leerling van bisschop Theofilus; verbrand door de Gotische koning Athanaric.' }],
  '9-16': [{ naam: 'Euphemia', titel: 'Grootmartelares (†304)', kort: 'Haar relieken bevestigden op wonderbare wijze de leer van Chalcedon.' }],
  '9-17': [{ naam: 'Sophia en haar dochters Geloof, Hoop en Liefde', titel: 'Martelaressen (†137)', kort: 'De drie kinderen stierven vóór hun moeder om het geloof.' }],
  '9-20': [{ naam: 'Eustathius Placidas', titel: 'Grootmartelaar (†118)', kort: 'Romeins veldheer, bekeerd door een hert met een kruis tussen het gewei.' }],
  '9-24': [
    { naam: 'Thecla', titel: 'Eerste martelares, gelijk aan de apostelen', kort: 'Leerlinge van Paulus te Iconium.' },
    { naam: 'Silouan de Athoniet', titel: 'Monnik (†1938)', kort: '„Houd uw geest in de hel en wanhoop niet.” Bad voor de hele wereld.' },
  ],
  '9-25': [{ naam: 'Sergius van Radonezj', titel: 'Ontslaping (†1392)', kort: 'Vader van het Russische kloosterleven; zegende Dmitri Donskoj vóór de slag op het Koelikovo-veld.' }],
  '9-26': [{ naam: 'Johannes de Theoloog', titel: 'Ontslaping', kort: 'De laatste apostel, ontslapen te Efeze op hoge leeftijd.' }],
  '9-28': [{ naam: 'Chariton de Belijder', titel: 'Abt (†350)', kort: 'Stichter van drie lauren in de Judese woestijn.' }],
  '9-30': [{ naam: 'Gregorius de Verlichter', titel: 'Bisschop van Armenië (†335)', kort: 'Doopte Armenië, de eerste christelijke natie.' }],
  '10-1': [{ naam: 'Romanos de Melode', titel: 'Diaken, hymnendichter (†556)', kort: 'Ontving van de Moeder Gods de gave van het zingen; dichter van het kerstkontakion.' }],
  '10-3': [{ naam: 'Dionysius de Areopagiet', titel: 'Bisschop van Athene, martelaar (†96)', kort: 'Bekeerd door Paulus op de Areopaag.' }],
  '10-6': [{ naam: 'Thomas', titel: 'Apostel', kort: '„Mijn Heer en mijn God” — predikte tot in Indië.' }],
  '10-7': [{ naam: 'Sergius en Bacchus', titel: 'Martelaren (†290)', kort: 'Romeinse officieren, vrienden en martelaren in Syrië.' }],
  '10-9': [{ naam: 'Jakobus, zoon van Alfeüs', titel: 'Apostel', kort: 'Eén van de Twaalf; gekruisigd in Egypte.' }],
  '10-14': [{ naam: 'Paraskeva van Servië (Petka)', titel: 'Asceet (11e eeuw)', kort: 'Patrones van Servië, Bulgarije en Roemenië; haar relieken rusten in Iași.' }],
  '10-18': [{ naam: 'Lucas', titel: 'Apostel en evangelist', kort: 'Arts en, volgens de overlevering, de eerste icoonschilder van de Moeder Gods.' }],
  '10-23': [{ naam: 'Jakobus, broeder des Heren', titel: 'Apostel, eerste bisschop van Jeruzalem', kort: 'Auteur van de brief van Jakobus en van de oudste Liturgie.' }],
  '10-26': [{ naam: 'Demetrius van Thessaloniki', titel: 'Grootmartelaar, myronvloeiende (†306)', kort: 'Beschermer van Thessaloniki; mirre stroomt uit zijn relieken.' }],
  '10-28': [
    { naam: 'Paraskevi van Iconium', titel: 'Grootmartelares (†3e eeuw)', kort: 'Patrones van de vrijdag en van de handel.' },
    { naam: 'Arsenius van Cappadocië', titel: 'Priester, wonderdoener (†1924)', kort: 'Doopte de latere starets Paisius.' },
  ],
  '11-1': [{ naam: 'Cosmas en Damianus van Azië', titel: 'Onbaatzuchtige artsen', kort: 'Genazen mensen en dieren gratis; aangeroepen bij ziekte.' }],
  '11-7': [{ naam: 'Willibrord', titel: 'Aartsbisschop van Utrecht, apostel der Friezen (†739)', kort: 'Uit Northumbrië gezonden verlichter van de Lage Landen; begraven in Echternach.', nl: true }],
  '11-8': [{ naam: 'Aartsengel Michaël en alle Lichaamloze Machten', titel: 'Synaxis', kort: 'Aanvoerder van de hemelse legerscharen en alle engelen.' }],
  '11-9': [{ naam: 'Nektarios van Aegina', titel: 'Metropoliet, wonderdoener (†1920)', kort: 'Moderne Griekse heilige; helper bij kanker; pelgrimsoord Aegina.' }],
  '11-11': [{ naam: 'Theodorus de Studiet', titel: 'Abt, belijder (†826)', kort: 'Hervormer van het kloosterleven, verdediger van de iconen.' }],
  '11-12': [
    { naam: 'Johannes de Barmhartige', titel: 'Patriarch van Alexandrië (†620)', kort: 'Noemde de armen „zijn heren”.' },
    { naam: 'Lebuinus van Deventer', titel: 'Priester, missionaris (†ca. 775)', kort: 'Predikte onder de Saksen aan de IJssel; stichter van de kerk van Deventer.', nl: true },
  ],
  '11-13': [{ naam: 'Johannes Chrysostomus', titel: 'Aartsbisschop van Constantinopel (†407)', kort: 'De Gouden Mond; auteur van de Liturgie die op de meeste dagen wordt gevierd.' }],
  '11-14': [{ naam: 'Filippus', titel: 'Apostel', kort: 'Bracht Nathanaël tot Christus; laatste dag vóór de Kerstvasten.' }],
  '11-16': [{ naam: 'Matteüs', titel: 'Apostel en evangelist', kort: 'De tollenaar die het eerste evangelie schreef.' }],
  '11-24': [{ naam: 'Catharina van Alexandrië', titel: 'Grootmartelares (†305)', kort: 'Bruid van Christus; het radwonder; haar relieken op de Sinaï.' }],
  '11-25': [{ naam: 'Clemens van Rome', titel: 'Paus, martelaar (†101)', kort: 'Derde opvolger van Petrus; brief aan Korinthe; verdronken met een anker.' }],
  '11-27': [{ naam: 'Icoon van de Moeder Gods „van het Teken” (Znamenie)', titel: 'Feest (Novgorod, 1170)', kort: 'Het icoon redde Novgorod tijdens de belegering.' }],
  '11-29': [{ naam: 'Radboud van Utrecht', titel: 'Bisschop (†917)', kort: 'Bisschop van Utrecht in ballingschap te Deventer; geleerde en dichter.', nl: true }],
  '11-30': [{ naam: 'Andreas de Eerstgeroepene', titel: 'Apostel', kort: 'Broer van Petrus; predikte aan de Zwarte Zee; patroon van het Oecumenisch Patriarchaat.' }],
  '12-4': [
    { naam: 'Barbara', titel: 'Grootmartelares (†306)', kort: 'Door haar eigen vader onthoofd; beschermster tegen een plotselinge dood.' },
    { naam: 'Johannes Damascenus', titel: 'Monnik, hymnendichter (†749)', kort: 'Verdediger van de iconen; dichter van de Paascanon.' },
  ],
  '12-5': [{ naam: 'Sabbas de Geheiligde', titel: 'Abt (†532)', kort: 'Stichter van de Grote Laura bij Jeruzalem; het Typikon van Sabbas ordent de diensten.' }],
  '12-6': [{ naam: 'Nicolaas van Myra', titel: 'Aartsbisschop, wonderdoener (†345)', kort: 'Sinterklaas: redder van zeelieden en kinderen, patroon van Amsterdam en van heel Rusland.' }],
  '12-7': [{ naam: 'Ambrosius van Milaan', titel: 'Bisschop, kerkvader (†397)', kort: 'Doopte Augustinus; vader van de Ambrosiaanse zang.' }],
  '12-9': [{ naam: 'Ontvangenis van de Moeder Gods door Anna', titel: 'Feest', kort: 'Na jaren van kinderloosheid ontvangt Anna Maria.' }],
  '12-12': [{ naam: 'Spyridon van Trimythous', titel: 'Bisschop, wonderdoener (†348)', kort: 'Herder-bisschop van Cyprus; op Nicea toonde hij met een dakpan de Drie-eenheid.' }],
  '12-13': [{ naam: 'Herman van Alaska', titel: 'Monnik (†1837)', kort: 'Eerste heilige van Amerika; beschermer van de Aleoeten.' }],
  '12-17': [{ naam: 'Profeet Daniël en de drie jongelingen', titel: 'Ananias, Azarias en Misaël', kort: 'In de leeuwenkuil en in de vuuroven; Zondag der Voorvaderen.' }],
  '12-20': [
    { naam: 'Ignatius van Antiochië', titel: 'Bisschop, martelaar (†107)', kort: 'De Goddrager; „Ik ben het tarwe van God, gemalen door de tanden der leeuwen.”' },
    { naam: 'Johannes van Kronstadt', titel: 'Priester, wonderdoener (†1908)', kort: 'Dagelijkse Liturgie, duizenden genezingen; „Mijn leven in Christus”.' },
  ],
  '12-22': [{ naam: 'Anastasia de Farmakolytria', titel: 'Grootmartelares (†304)', kort: 'Bezocht gevangenen; „bevrijdster van vergif”, patrones van gevangenen.' }],
  '12-24': [{ naam: 'Eugenia van Rome', titel: 'Martelares (†262)', kort: 'Leefde als monnik onder de naam Eugenius; vooravond van Kerstmis.' }],
  '12-26': [{ naam: 'Synaxis van de Moeder Gods', titel: 'Feest', kort: 'Daags na Kerstmis: Jozef de Verloofde, koning David en Jakobus herdacht.' }],
  '12-27': [{ naam: 'Stefanus', titel: 'Protomartelaar, aartsdiaken (†34)', kort: 'De eerste die zijn geloof met zijn bloed bezegelde; gestenigd te Jeruzalem.' }],
  '12-29': [{ naam: 'De 14.000 kinderen van Bethlehem', titel: 'Martelaren', kort: 'Door Herodes gedood; de eerste onschuldige martelaren om Christus.' }],
};

export interface HeiligeMetDatum extends Heilige {
  md: string;
}

export const ALLE_HEILIGEN: HeiligeMetDatum[] = Object.entries(HEILIGEN).flatMap(([md, lijst]) =>
  lijst.map((h) => ({ ...h, md })),
);
